services:
  # 1. Database for Spring Boot App
  user-management-db:
    image: postgres:15
    container_name: app-postgres
    environment:
      POSTGRES_DB: user_management_db
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak123
    ports:
      - "5434:5432"
    volumes:
      - app_db_data:/var/lib/postgresql/data

  # 2. Database for Keycloak
  keycloak-db:
    image: postgres:15
    container_name: keycloak-postgres
    environment:
      POSTGRES_DB: keycloak_db
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak123

    volumes:
#      - ./keycloak-data:/var/lib/postgresql/data
      - keycloak_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U keycloak -d keycloak_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  # 3. Keycloak Server
  keycloak:
    image: quay.io/keycloak/keycloak:26.7.0
    container_name: keycloak_server
    command:
      - start-dev
      - --verbose
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: keycloak-db
      KC_DB_URL_DATABASE: keycloak_db
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak123
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin123
      KC_LOG_LEVEL: DEBUG

      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      KAFKA_USER_EVENTS_TOPIC: user-provisioning-events
    ports:
      - "8081:8080"
    depends_on:
      keycloak-db:
        condition: service_healthy
      kafka:
        condition: service_started
    volumes:
      - ./providers/keycloak-user-provisioning-1.0-SNAPSHOT.jar:/opt/keycloak/providers/keycloak-user-provisioning.jar
      - ./providers/keycloak-event-listener-1.0-SNAPSHOT.jar:/opt/keycloak/providers/custom-logging-listener.jar

      - ./providers/keycloak-field-validator-1.0.0.jar:/opt/keycloak/providers/keycloak-field-validator.jar

      - ./src/main/resources/themes/my-portal-theme:/opt/keycloak/themes/my-portal-theme

  # 4. Kafka and Kafka UI
  kafka:
    image: apache/kafka:4.1.0
    container_name: kafka
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller

      KAFKA_LISTENERS: PLAINTEXT://:9092,HOST://:29092,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,HOST://localhost:29092

      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER

      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,HOST:PLAINTEXT,CONTROLLER:PLAINTEXT

      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "8090:8080"
    depends_on:
      - kafka
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092

  # 5. OpenLDAP Server
  openldap:
    image: osixia/openldap:1.5.0
    container_name: openldap
    restart: unless-stopped

    environment:
      LDAP_ORGANISATION: "LinkDev"
      LDAP_DOMAIN: "linkdev.local"

      LDAP_ADMIN_USERNAME: admin
      LDAP_ADMIN_PASSWORD: admin123

      LDAP_CONFIG_PASSWORD: config123

      LDAP_BASE_DN: dc=linkdev,dc=local

      LDAP_TLS: "false"

    ports:
      - "389:389"

    volumes:
      - openldap_data:/var/lib/ldap
      - openldap_config:/etc/ldap/slapd.d


  phpldapadmin:
    image: osixia/phpldapadmin:0.9.0
    container_name: phpldapadmin
    restart: unless-stopped

    environment:
      PHPLDAPADMIN_LDAP_HOSTS: openldap
      PHPLDAPADMIN_HTTPS: "false"

    ports:
      - "8082:80"

    depends_on:
      - openldap


volumes:
  app_db_data:      # Separate storage for app
  keycloak_db_data: # Separate storage for Keycloak
  openldap_data:    # Separate storage for OpenLDAP
  openldap_config:  # Separate storage for OpenLDAP configuration