spring.application.name=user-management

# 1. Database Connection Settings
spring.datasource.url=jdbc:postgresql://localhost:5434/user_management_db
spring.datasource.username=keycloak
spring.datasource.password=keycloak123
spring.datasource.driver-class-name=org.postgresql.Driver

# 2. JPA / Hibernate Settings
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

keycloak.realm=task-management
keycloak.server-url=http://localhost:8081
keycloak.client-id=admin-cli
keycloak.username=admin
keycloak.password=admin123

spring.security.oauth2.resourceserver.jwt.issuer-uri=${keycloak.server-url}/realms/${keycloak.realm}

# 3. Server Port
server.port=9090

springdoc.use-fqn=true
