ALTER TABLE user_types ADD COLUMN IF NOT EXISTS allowed_to_self_signup BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE user_types ADD COLUMN IF NOT EXISTS requires_admin_approval BOOLEAN NOT NULL DEFAULT FALSE;
